# Generated by Django 5.1.4 on 2025-12-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backlit_keyboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'Brand New'), ('Refurbished', 'Ex-UK Refurbished'), ('Used', 'Used - Good Condition')], default='Refurbished', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='fingerprint_sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(default='Intel Core i5', help_text='e.g. Intel Core i5 6th Gen', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('4GB', '4GB'), ('8GB', '8GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], default='8GB', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.CharField(default='14 inch', help_text='e.g. 14 inch FHD', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default='256GB', help_text='e.g. 256GB', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_type',
            field=models.CharField(choices=[('SSD', 'SSD (Fast)'), ('HDD', 'HDD (Large Storage)'), ('NVMe', 'NVMe (Super Fast)')], default='SSD', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='touchscreen',
            field=models.BooleanField(default=False),
        ),
    ]
