# Generated by Django 6.0 on 2026-01-05 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_backlit_keyboard_product_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='laptop_type',
            field=models.CharField(choices=[('Standard', 'Standard Laptop'), ('X360', 'X360 / Convertible'), ('Detachable', 'Detachable'), ('Slim', 'Ultrabook / Slim')], default='Standard', help_text='Physical style (e.g. X360, Slim)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.CharField(choices=[('Everyday', 'Everyday Laptops'), ('Business', 'Business/Enterprise Laptops'), ('Premium', 'Premium Laptops'), ('Gaming', 'Gaming Laptops'), ('Student', 'Student Laptops')], default='Everyday', help_text='Best use case (e.g. Student, Gaming)', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer Name', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product')),
            ],
        ),
    ]
